### ISSUE TITLE
希望大佬建个QQ群 CURD做一个后台插件

### ISSUE THREAD

**Issue by vsic** [wolf-leo/EasyAdmin8#2]
新手没有地方可以交流，肯请大佬建个群吧
我不论是windows还是linux 都没有办法实现用curd命令生成表，就是自己建好表了用curd命令生成表也是会报错，能不能给指点一下，后台都可以正常访问登陆使用。
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'easyadmin8.ea8_spm_text' doesn't exist
cdall@qq.com

**Comment by wolf-leo** [comment]
![EasyAdmin8（ThinkPHP）交流群群聊二维码](https://github.com/wolf-leo/EasyAdmin8/assets/37436228/240b7ee9-87d0-48c0-ac6c-a32bc94b87df)

**Comment by wolf-leo** [comment]
close
