### ISSUE TITLE
修改后台入口之后丢失 session 跳转找不到控制器

### ISSUE THREAD

**Issue by zc0350** [wolf-leo/EasyAdmin8#7]
因为想长期使用这套系统~~~

CheckLogin.php
             $this->error('登录已过期，请重新登录', [], __url('admin/login/index'));
建议修改
   $this->error('登录已过期，请重新登录', [], __url(env("EASYADMIN.ADMIN").'/login/index'));

**Comment by wolf-leo** [comment]
Thanks fixed  772ffc6328227ddd9e157e93aee0e3caba07d18e
