### ISSUE TITLE
requirejs更新依赖请求

### ISSUE THREAD

**Issue by Rodots** [wolf-leo/EasyAdmin8#8]
[requirejs](https://github.com/requirejs/requirejs)已经更新到2.3.7版本，时隔6年，框架的依赖也可以同步更新了，包括vue2的依赖和jQuery的依赖等等...

**Comment by wolf-leo** [comment]
要考虑兼容性 - - 这个我要详细测试下

**Comment by wolf-leo** [comment]
> 就更新了3行代码，一行注释里面的`valye`改`value`，还有两行代码，无缝升级，可以说：更不更新都无所谓。。

那就不更新了 ..
